// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM39GCQV-rF7bbfmQ3FKkc1_JD5v5o9HE',
    appId: '1:840761135635:web:f68ca80118d64242c3e5e6',
    messagingSenderId: '840761135635',
    projectId: 'ayn2023-a346d',
    authDomain: 'ayn2023-a346d.firebaseapp.com',
    databaseURL: 'https://ayn2023-a346d-default-rtdb.firebaseio.com',
    storageBucket: 'ayn2023-a346d.appspot.com',
    measurementId: 'G-XE6G3QCE1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmoZb1CfIgr0qddwhnfw_zAmU_m8Nn4gw',
    appId: '1:840761135635:android:2ee8e15bcc81b527c3e5e6',
    messagingSenderId: '840761135635',
    projectId: 'ayn2023-a346d',
    databaseURL: 'https://ayn2023-a346d-default-rtdb.firebaseio.com',
    storageBucket: 'ayn2023-a346d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb5jsJ2ppFaTAHPmxPhdaoIslc55P2JYg',
    appId: '1:840761135635:ios:e7bb457f64f75c40c3e5e6',
    messagingSenderId: '840761135635',
    projectId: 'ayn2023-a346d',
    databaseURL: 'https://ayn2023-a346d-default-rtdb.firebaseio.com',
    storageBucket: 'ayn2023-a346d.appspot.com',
    iosClientId: '840761135635-okvc27rp1gaq7atmgb6af8bk0uvtkd2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.ayn3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb5jsJ2ppFaTAHPmxPhdaoIslc55P2JYg',
    appId: '1:840761135635:ios:e7bb457f64f75c40c3e5e6',
    messagingSenderId: '840761135635',
    projectId: 'ayn2023-a346d',
    databaseURL: 'https://ayn2023-a346d-default-rtdb.firebaseio.com',
    storageBucket: 'ayn2023-a346d.appspot.com',
    iosClientId: '840761135635-okvc27rp1gaq7atmgb6af8bk0uvtkd2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.ayn3',
  );
}
